name = "pte-di-trainer"
main = "worker.js"
compatibility_date = "2024-03-08"

[env.production.vars]
TENCENT_REGION = "ap-guangzhou"

# 在部署前需要设置以下 secrets:
# wrangler secret put TENCENT_SECRET_ID
# wrangler secret put TENCENT_SECRET_KEY